### ISSUE TITLE
Apple M1 (arm) support

### ISSUE THREAD

**Issue by grainz** [dehesselle/chatty#8]
Would it be possible to build this with M1 (arm) support?
There are native java builds available.
https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk

**Comment by dehesselle** [comment]
Are you experiencing issues because of Rosetta 2 or are you just asking generally?

I do not own any Apple Silicon based hardware, so I haven't spent any time looking into this.

**Comment by grainz** [comment]
I am not experiencing any issues for the moment. More of a general question. However, Apple plans on removing Rosetta 2 eventually. I was previously running the JAR file manually but then I found this project to make that process easier.

If/when I have time, I can try to implement it and create a PR.

**Comment by dehesselle** [comment]
Don't worry, I will have moved to Apple Silicon based hardware long before they remove Rosetta 2. I'm waiting for a machine with 32 GiB of RAM.

**Comment by grainz** [comment]
Didn't mean to close this.
I was able to build this successfully with as a Apple M1 native application.

EDIT: I didn't have to modify anything. I already have java and python installed (M1/arm builds). build.sh ran without error.

**Comment by dehesselle** [comment]
I own a Mac mini M1 now, couldn't wait any longer. There will be a native version soon.

**Comment by dehesselle** [comment]
I just published the first version of Chatty for arm64 architecture.
https://github.com/dehesselle/chatty/releases/tag/v0.14_mac46

It's a preview release because my build scripts need some more work.

**Comment by grainz** [comment]
> I just published the first version of Chatty for arm64 architecture.
> https://github.com/dehesselle/chatty/releases/tag/v0.14_mac46
> 
> It's a preview release because my build scripts need some more work.

downloaded and ran just fine. usually security warning if i'm sure to open it. Activity Monitor shows Apple instead of Intel. Keep up the good work.

**Comment by dehesselle** [comment]
Thanks for testing!
The security warning will always be there, the important thing is the "Apple scanned it for malware and found none" part inside this warning, proving that it is signed and notarized. (It may not mean much to you as you don't know me, but for me it's my reputation.)

I'll keep this issue open until l've done my cleanup work and can release Intel and ARM side by side.

**Comment by grainz** [comment]
I understand what's happening behind the scenes. Just putting it out there for anyone reading that's what happens. I look forward to more releases.

**Comment by grainz** [comment]
An update: I notice the app runs with high RAM usage. I would notice it can easily reach above 1-2GB of RAM usage if I leave the app running overnight. This is a Java thing (unfortunately always will be). I know there are runtime options you can add to limit RAM usage. Have you ever looked into this?

**Comment by dehesselle** [comment]
v0.15 released for both architectures, closing this.

RAM usage: have you talked to upstream about that? Unless they have some recommended settings that I'm missing, I don't think I'm going to anything about it.
